services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: backend-nodejs-auroraworld-dev
    env_file:
      - .env
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: backend-nodejs-auroraworld-prod
    env_file:
      - .env
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    volumes:
      - /app/node_modules
    restart: always
